# -*- coding: utf-8 -*-
"""Semantic chunking of a youtube video.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GGWL1EI_y6WfneWlZgHZwJ3Juhx72xf1
"""

!pip install yt-dlp



"""Youtube video has been downloaded , trying to extract audio from the youtube video

Installing ffmpeg to extract audio from the youtube video
"""

!apt-get install ffmpeg

"""To download the youtube video"""

# Use yt-dlp to download the video
!yt-dlp -o 'video.mp4' https://www.youtube.com/watch?v=Sby1uJ_NFIY

"""To list if the video has been downloaded or not!"""

# List the files to ensure the video is downloaded
!ls -lh

"""Extracting audio from the youtube video using ffmpeg"""

!ls

# Extract audio from the video
!ffmpeg -i video.mp4.mkv -q:a 0 -map a audio.mp3

!ls

"""List to check if audio file is available or not"""

!ls -lh

"""Code to convert speech to text"""

!pip install SpeechRecognition

!pip install pydub

from pydub import AudioSegment
audio = AudioSegment.from_file("audio.mp3")
audio.export("audio.wav", format="wav")

pip install git+https://github.com/openai/whisper

import whisper
model = whisper.load_model("medium.en")

!pip install torch
!pip install transformers

import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'
model = whisper.load_model('medium').to(device)

# Ensure that a GPU is available
device = "cuda" if torch.cuda.is_available() else "cpu"

# Load the medium Whisper model with FP16 precision
model = whisper.load_model("medium", device=device)

# Step 3: Transcribe the audio file
result = model.transcribe("audio.wav", fp16=True,word_timestamps = True)

# Print the transcription
segments = result["segments"]
for segment in segments:
    print(
        f"Start: {segment['start']}s, "
        f"End: {segment['end']}s, "
        f"Text: {segment['text']}"
    )

print(device)
print(torch.cuda.is_available())

from pydub import AudioSegment

audio = AudioSegment.from_wav("audio.wav")

segments = result["segments"]

max_duration = 15 * 1000  # 15 seconds

chunks = []

current_audio = AudioSegment.empty()
current_text = ""
current_start = None
current_end = None

for segment in segments:

    start_time = int(segment["start"] * 1000)
    end_time = int(segment["end"] * 1000)
    text = segment["text"].strip()

    segment_audio = audio[start_time:end_time]

    # If adding this segment makes the chunk longer than 15 sec
    if (
        current_start is not None
        and len(current_audio) + len(segment_audio) > max_duration
    ):

        chunks.append({
            "audio": current_audio,
            "text": current_text,
            "start": current_start / 1000,
            "end": current_end / 1000
        })

        current_audio = AudioSegment.empty()
        current_text = ""
        current_start = None

    # Start a new chunk
    if current_start is None:
        current_start = start_time

    current_audio += segment_audio

    if current_text:
        current_text += " " + text
    else:
        current_text = text

    current_end = end_time


# Add final chunk
if current_start is not None:

    chunks.append({
        "audio": current_audio,
        "text": current_text,
        "start": current_start / 1000,
        "end": current_end / 1000
    })

for i, chunk in enumerate(chunks):

    file_name = f"chunk_{i}.wav"

    chunk["audio"].export(
        file_name,
        format="wav"
    )

    chunk["file"] = file_name

    print(
        f"Chunk {i}: "
        f"{chunk['start']:.2f}s - "
        f"{chunk['end']:.2f}s"
    )

    print(chunk["text"])
    print()

!pip install -q sentence-transformers faiss-cpu

from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

chunk_texts = []

for chunk in chunks:
    chunk_texts.append(chunk["text"])

print("Number of chunks:", len(chunk_texts))

print(chunk_texts[0])

embeddings = embedding_model.encode(
    chunk_texts,
    convert_to_numpy=True,
    normalize_embeddings=True
)

print(embeddings.shape)

import faiss

dimension = embeddings.shape[1]

index = faiss.IndexFlatIP(dimension)

index.add(embeddings)

print("Chunks stored in FAISS:", index.ntotal)

def search_video(query, k=3):

    query_embedding = embedding_model.encode(
        [query],
        convert_to_numpy=True,
        normalize_embeddings=True
    )

    scores, indices = index.search(
        query_embedding,
        k
    )

    results = []

    for score, idx in zip(scores[0], indices[0]):

        chunk = chunks[idx]

        results.append({
            "chunk": idx,
            "text": chunk["text"],
            "start": chunk["start"],
            "end": chunk["end"],
            "score": float(score),
            "file": chunk["file"]
        })

    return results

results = search_video(
    "What does the speaker say about artificial intelligence?"
)

for result in results:

    print("Chunk:", result["chunk"])

    print(
        f"Time: {result['start']:.2f}s - "
        f"{result['end']:.2f}s"
    )

    print(
        f"Similarity: {result['score']:.3f}"
    )

    print(result["text"])

    print("-" * 50)

video_id = "Sby1uJ_NFIY"

from IPython.display import display, Markdown

for result in results:

    start_seconds = int(result["start"])

    youtube_link = (
        f"https://www.youtube.com/watch?"
        f"v={video_id}&t={start_seconds}s"
    )

    print("Chunk:", result["chunk"])

    print(
        f"Time: {result['start']:.2f}s - "
        f"{result['end']:.2f}s"
    )

    print(
        f"Similarity: {result['score']:.3f}"
    )

    print(result["text"])

    display(
        Markdown(
            f"[Open video at {start_seconds} seconds]({youtube_link})"
        )
    )

    print("-" * 50)

test_queries = [
    "What does the speaker say about AI?",
    "How is AI used in business?",
    "What does the speaker say about generative AI?",
    "What opportunities does AI create?",
    "Why should people leverage AI?"
]

for query in test_queries:
    print("QUERY:", query)

    results = search_video(query, k=3)

    for result in results:
        print(
            result["chunk"],
            result["start"],
            result["text"]
        )

    print("-" * 50)

expected_ranges = {
    "What does the speaker say about AI?": (1120, 1160),
    "How is AI used in business?": (1110, 1150),
    "What does the speaker say about generative AI?": (180, 220),

    # Add more
     "How does the speaker describe organizations using AI?":
        (1151, 1169),

    "What does the speaker say about people using AI?":
        (1137, 1152),

    "Why does the speaker call AI a tool?":
        (1123, 1137),

    "What business processes are discussed?":
        (1181, 1223),

    "What does the speaker say about innovation?":
        (158, 205),

    "What does the speaker say about technology adoption?":
        (1490, 1504),

    "What does the speaker say about generative AI opportunities?":
        (190, 236),

    "How can AI make people more effective?":
        (1137, 1169),

    "What does the speaker say about companies using AI?":
        (1151, 1169),

    "What change does AI create for organizations?":
        (1151, 1169),

    "What does the speaker say about building something with AI?":
        (190, 205),

    "How should businesses use AI?":
        (1123, 1169),

    "What does the speaker say about the future of AI?":
        (1137, 1169),

    "What advantage do people using AI have?":
        (1137, 1152),

    "What does the speaker say about incorporating AI into work?":
        (1123, 1169)
}

def is_correct(results, expected_start, expected_end):
    """
    Returns True if at least one of the top-k retrieved chunks
    overlaps with the expected correct timestamp range.
    """

    for result in results:

        retrieved_start = result["start"]
        retrieved_end = result["end"]

        # Check whether the retrieved chunk overlaps
        # with the expected timestamp range
        if (
            retrieved_start <= expected_end
            and retrieved_end >= expected_start
        ):
            return True

    return False


results_summary = {}

for query, expected_range in expected_ranges.items():

    # Search the video using your already-created FAISS system
    results = search_video(query, k=3)

    expected_start, expected_end = expected_range

    correct = is_correct(
        results,
        expected_start,
        expected_end
    )

    results_summary[query] = correct

    print("Query:", query)
    print("Expected range:", expected_range)
    print("Correct:", correct)

    print("Top 3 retrieved chunks:")

    for result in results:
        print(
            f"Chunk {result['chunk']} | "
            f"{result['start']:.2f}s - {result['end']:.2f}s | "
            f"Similarity: {result['score']:.3f}"
        )
        print(result["text"])
        print()

    print("=" * 80)


correct_queries = sum(results_summary.values())
total_queries = len(results_summary)

recall_at_3 = correct_queries / total_queries


print("\nFINAL EVALUATION")
print("----------------")
print("Correct queries:", correct_queries)
print("Total queries:", total_queries)
print(f"Recall@3: {recall_at_3:.3f}")
print(f"Recall@3 percentage: {recall_at_3 * 100:.1f}%")

expected_ranges = {

    "What are the two main things the company plans to spend funding on?":
        (303, 330),

    "What is OpenHati trying to do with open-source language models?":
        (383, 425),

    "Which base model is OpenHati currently built on?":
        (428, 439),

    "What kind of developer platform does Sarvam plan to build?":
        (476, 515),

    "What does Sarvam mean by being a full-stack generative AI company?":
        (533, 562),

    "Why does the speaker believe smaller models can be useful?":
        (600, 631),

    "Why does the speaker describe India as a voice-first nation?":
        (647, 661),

    "Why are smaller AI models especially important in India?":
        (662, 688),

    "How can AI combine with India's digital public infrastructure?":
        (688, 707),

    "What are some of the main AI application areas mentioned for India?":
        (833, 878),

    "What is the speaker's first prediction about automated customer service?":
        (913, 924),

    "What does the speaker predict will happen to the GPU shortage?":
        (921, 942),

    "Why does the speaker think access to GPUs will improve?":
        (913, 948),

    "Why might some companies suddenly fall behind because of AI?":
        (1119, 1170),

    "What does the speaker say about competitors reimagining business processes?":
        (1172, 1202),

    "What customized component has Sarvam built for Indian languages?":
        (1281, 1298),

    "Is Sarvam only fine-tuning existing models?":
        (1298, 1320),

    "What problem does OpenHati try to solve with existing open-source models?":
        (1330, 1341),

    "How does the speaker think India can benefit from generative AI and DPI together?":
        (1391, 1436),

    "What does the speaker say people need to learn in order to use AI effectively?":
        (1504, 1563)
}

results_summary = {}

for query, expected_range in expected_ranges.items():

    results = search_video(query, k=3)

    expected_start, expected_end = expected_range

    results_summary[query] = is_correct(
        results,
        expected_start,
        expected_end
    )

correct_queries = sum(results_summary.values())
total_queries = len(results_summary)

recall_at_3 = correct_queries / total_queries

print("Correct queries:", correct_queries)
print("Total queries:", total_queries)
print(f"Recall@3: {recall_at_3:.3f}")
print(f"Recall@3 percentage: {recall_at_3 * 100:.1f}%")

failed_queries = [
    query
    for query, correct in results_summary.items()
    if not correct
]

print("Failed queries:")
for query in failed_queries:
    print("-", query)

for query in failed_queries:

    print("\nQUERY:", query)
    print("Expected range:", expected_ranges[query])

    results = search_video(query, k=3)

    for result in results:
        print(
            f"{result['start']:.2f}s - "
            f"{result['end']:.2f}s | "
            f"score={result['score']:.3f}"
        )
        print(result["text"])
        print()

# -----------------------------
# 1. Create 30-second chunks
# -----------------------------

def create_chunks_from_segments(segments, max_seconds):

    new_chunks = []

    current_text = ""
    current_start = None
    current_end = None

    for segment in segments:

        start = segment["start"]
        end = segment["end"]
        text = segment["text"].strip()

        if current_start is None:
            current_start = start

        # If adding this segment would make the chunk too long
        if end - current_start > max_seconds:

            if current_text:
                new_chunks.append({
                    "text": current_text,
                    "start": current_start,
                    "end": current_end
                })

            # Start a new chunk with the current segment
            current_text = text
            current_start = start
            current_end = end

        else:

            if current_text:
                current_text += " " + text
            else:
                current_text = text

            current_end = end

    # Save final chunk
    if current_text:
        new_chunks.append({
            "text": current_text,
            "start": current_start,
            "end": current_end
        })

    return new_chunks


chunks_30 = create_chunks_from_segments(
    segments,
    max_seconds=30
)

print("Number of 30-second chunks:", len(chunks_30))


# -----------------------------
# 2. Create embeddings
# -----------------------------

texts_30 = [
    chunk["text"]
    for chunk in chunks_30
]

embeddings_30 = embedding_model.encode(
    texts_30,
    convert_to_numpy=True,
    normalize_embeddings=True
)

print("Embedding shape:", embeddings_30.shape)


# -----------------------------
# 3. Build a new FAISS index
# -----------------------------

import faiss

dimension_30 = embeddings_30.shape[1]

index_30 = faiss.IndexFlatIP(
    dimension_30
)

index_30.add(
    embeddings_30
)

print(
    "Chunks stored in 30-second FAISS index:",
    index_30.ntotal
)


# -----------------------------
# 4. Search function for 30-sec chunks
# -----------------------------

def search_video_30(query, k=3):

    query_embedding = embedding_model.encode(
        [query],
        convert_to_numpy=True,
        normalize_embeddings=True
    )

    scores, indices = index_30.search(
        query_embedding,
        k
    )

    results = []

    for score, idx in zip(
        scores[0],
        indices[0]
    ):

        chunk = chunks_30[idx]

        results.append({
            "chunk": idx,
            "text": chunk["text"],
            "start": chunk["start"],
            "end": chunk["end"],
            "score": float(score)
        })

    return results


# -----------------------------
# 5. Evaluate Recall@3
# -----------------------------

results_summary_30 = {}

for query, expected_range in expected_ranges.items():

    results = search_video_30(
        query,
        k=3
    )

    expected_start, expected_end = expected_range

    results_summary_30[query] = is_correct(
        results,
        expected_start,
        expected_end
    )


correct_queries_30 = sum(
    results_summary_30.values()
)

total_queries_30 = len(
    results_summary_30
)

recall_at_3_30 = (
    correct_queries_30
    / total_queries_30
)


print("\n30-SECOND EVALUATION")
print("--------------------")
print(
    "Correct queries:",
    correct_queries_30
)
print(
    "Total queries:",
    total_queries_30
)
print(
    f"Recall@3: "
    f"{recall_at_3_30:.3f}"
)
print(
    f"Recall@3 percentage: "
    f"{recall_at_3_30 * 100:.1f}%"
)

failed_queries_30 = [
    query
    for query, correct in results_summary_30.items()
    if not correct
]

print("Failed queries for 30-second chunks:")

for query in failed_queries_30:
    print("-", query)

for query in failed_queries_30:

    print("\nQUERY:", query)
    print("Expected range:", expected_ranges[query])

    results = search_video_30(query, k=3)

    for result in results:
        print(
            f"{result['start']:.2f}s - "
            f"{result['end']:.2f}s | "
            f"score={result['score']:.3f}"
        )
        print(result["text"])
        print()

from sentence_transformers import SentenceTransformer

embedding_model_mpnet = SentenceTransformer(
    "all-mpnet-base-v2"
)

texts_30 = [
    chunk["text"]
    for chunk in chunks_30
]

embeddings_30_mpnet = embedding_model_mpnet.encode(
    texts_30,
    convert_to_numpy=True,
    normalize_embeddings=True
)

import faiss

dimension_mpnet = embeddings_30_mpnet.shape[1]

index_30_mpnet = faiss.IndexFlatIP(
    dimension_mpnet
)

index_30_mpnet.add(
    embeddings_30_mpnet
)


def search_video_30_mpnet(query, k=3):

    query_embedding = embedding_model_mpnet.encode(
        [query],
        convert_to_numpy=True,
        normalize_embeddings=True
    )

    scores, indices = index_30_mpnet.search(
        query_embedding,
        k
    )

    results = []

    for score, idx in zip(
        scores[0],
        indices[0]
    ):

        chunk = chunks_30[idx]

        results.append({
            "chunk": idx,
            "text": chunk["text"],
            "start": chunk["start"],
            "end": chunk["end"],
            "score": float(score)
        })

    return results


results_summary_30_mpnet = {}

for query, expected_range in expected_ranges.items():

    results = search_video_30_mpnet(
        query,
        k=3
    )

    expected_start, expected_end = expected_range

    results_summary_30_mpnet[query] = is_correct(
        results,
        expected_start,
        expected_end
    )


correct_mpnet = sum(
    results_summary_30_mpnet.values()
)

total_mpnet = len(
    results_summary_30_mpnet
)

recall_mpnet = (
    correct_mpnet / total_mpnet
)

print("MPNet 30-second evaluation")
print("--------------------------")
print("Correct queries:", correct_mpnet)
print("Total queries:", total_mpnet)
print(f"Recall@3: {recall_mpnet:.3f}")
print(f"Recall@3 percentage: {recall_mpnet * 100:.1f}%")

failed_queries_mpnet = [
    query
    for query, correct in results_summary_30_mpnet.items()
    if not correct
]

print("Failed MPNet queries:")

for query in failed_queries_mpnet:
    print("-", query)